version: '3'
services:
  pgadmin:
    container_name: db-postgres-admin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "120:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=lenoxy@gmx.ch
      - PGADMIN_DEFAULT_PASSWORD=admin
    networks:
      - database
    volumes:
      - db-postgres-admin-data:/var/lib/pgadmin/data

  postgres:
    container_name: db-postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=db-postgres
      - POSTGRES_USER=db-postgres
    networks:
      - database
    volumes:
      - db-postgres-data:/var/lib/postgresql/data

volumes:
  db-postgres-data:
  db-postgres-admin-data:
    
networks:
  database:
